runtime: python
vm: true
threadsafe: true
manual_scaling:
  instances: 1
entrypoint: python main.py $PORT

runtime_config:
  python_version: 2

resources:
  cpu: .5
  memory_gb: .18
  disk_size_gb: 10
